use failure::Error;
use nekton::run;

fn main() -> Result<(), Error> {
    run()?;

    Ok(())
}
